Table rawbeans {
  id integer [primary key]
  name varchar
  price integer 
  amount integer 
  description varchar
  seller varchar
  country varchar
  location varchar
  process_method varchar
  ranch varchar
  species varchar
  created_at timestamp
}

Table bake {
  id integer [primary key]
  rawbeans_id integer [ref: > rawbeans.id]
  weight_before integer
  description varchar
  weight_loss float
  pot_num integer
  feed_back varchar
  created_at timestamp
}

Table users {
  id integer [primary key]
  username varchar
  created_at timestamp
}

Table transactions {
  id integer [primary key]
  buyer_id integer [ref: > users.id]
  bake_id integer [ref: > bake.id]
  price integer
  created_at timestamp
}